### ISSUE TITLE
Crashes after being idle for a while

### ISSUE THREAD

**Issue by dippnerd** [Siddharth11/iTunes-Remote#5]
Hey, it's me again, sorry! Just wondering if you've run into this. I've been leaving this running, music playing or not, but at some point (haven't narrowed down how long it takes) it errors out. The status seems to fall into an undefined state for some reason, but nothing changed on the machine, it's a Mac Mini sitting idle otherwise. I'm trying to familiarize myself with the various modules, but hoping you might have some insight. 

Here is the output:

/Users/aaron/iTunes-Remote/node_modules/node-osascript/lib/index.js:14
  stream.on('data', function( chunk ){
        ^

TypeError: Cannot read property 'on' of undefined
    at bufferStream (/Users/aaron/iTunes-Remote/node_modules/node-osascript/lib/index.js:14:9)
    at execute (/Users/aaron/iTunes-Remote/node_modules/node-osascript/lib/index.js:31:19)
    at Object.execute (/Users/aaron/iTunes-Remote/node_modules/node-osascript/lib/index.js:69:5)
    at osa.execute (/Users/aaron/iTunes-Remote/server/serverSideEvents.js:85:25)
    at ChildProcess.<anonymous> (/Users/aaron/iTunes-Remote/node_modules/node-osascript/lib/index.js:49:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by Siddharth11** [comment]
@dippnerd I've also encountered it once. Not sure though how to solve it. The problem seems to be in the npm package I'm using to execute applescript commands.

**Comment by dippnerd** [comment]
Yeah, it doesn't seem specific to your program from what I can tell, but wanted to make sure it's not just me :)
